const fs = require("node:fs");
const path = require("node:path");
const { loadRegister, summarize } = require("./scope-status");

const root = path.join(__dirname, "..");
const readJson = (relativePath) => JSON.parse(fs.readFileSync(path.join(root, relativePath), "utf8"));
const loadRoadmap = () => readJson("planning/roadmap.json");

function validateRoadmap(roadmap, register) {
  if (roadmap.schemaVersion !== 1 || !Array.isArray(roadmap.stages) || roadmap.stages.length === 0) {
    throw new Error("Unsupported or empty roadmap");
  }
  const packageMap = new Map(register.packages.map((item) => [item.id, item]));
  const expectedIds = register.packages.map((item, index) => `P${String(index).padStart(2, "0")}`);
  if (register.packages.some((item, index) => item.id !== expectedIds[index])) {
    throw new Error("Work-package IDs must be contiguous and ordered");
  }
  const stageIds = new Set();
  const seenPackages = new Set();
  for (const stage of roadmap.stages) {
    if (!/^S\d{2,}$/.test(stage.id) || stageIds.has(stage.id) || !stage.name ||
        !Array.isArray(stage.packageIds) || stage.packageIds.length === 0) {
      throw new Error(`Invalid roadmap stage: ${stage.id || "missing"}`);
    }
    for (const packageId of stage.packageIds) {
      if (!packageMap.has(packageId)) throw new Error(`${stage.id} references missing ${packageId}`);
      if (seenPackages.has(packageId)) throw new Error(`${packageId} appears in multiple roadmap stages`);
      seenPackages.add(packageId);
    }
    stageIds.add(stage.id);
  }
  const missing = [...packageMap.keys()].filter((id) => !seenPackages.has(id));
  if (missing.length) throw new Error(`Roadmap omits packages: ${missing.join(", ")}`);
  const active = packageMap.get(roadmap.activePackageId);
  if (!active || active.status === "done") throw new Error("Roadmap active package must exist and be unfinished");
  for (const item of register.packages) {
    if (!item.phase?.trim() || !item.name?.trim()) throw new Error(`${item.id} lacks phase or name`);
  }
  return { active, packageMap };
}

function stageStatus(stage, packageMap, activePackageId) {
  const packages = stage.packageIds.map((id) => packageMap.get(id));
  if (stage.packageIds.includes(activePackageId)) return "ACTIVE";
  if (packages.every((item) => item.status === "done")) return "DONE";
  if (packages.some((item) => item.status !== "planned")) return "PARTIAL";
  return "PLANNED";
}

const estimateLabel = (item) => {
  const baseline = `${item.estimatedTokens / 1000}k`;
  return item.revisedEstimateTokens ? `${baseline} -> ${item.revisedEstimateTokens / 1000}k` : baseline;
};

function renderPlan(roadmap, register, packageMetadata) {
  const { active, packageMap } = validateRoadmap(roadmap, register);
  const scope = summarize(register);
  const lines = [
    "# LTP Workbench - Plan Status",
    "",
    "Generated from `planning/roadmap.json` and `planning/work-packages.json`.",
    "Do not edit this file manually; run `npm run plan:write`.",
    "",
    `Current build: \`${packageMetadata.ltpBuild.id}\` - ${packageMetadata.ltpBuild.name}`,
    `Active package: \`${active.id}\` - ${active.name}`,
    `Weighted scope complete: **${scope.progressPercent.toFixed(1)}%**`,
    `Portfolio: ${scope.statusCounts.done} done, ${scope.statusCounts.partial} partial, ` +
      `${scope.statusCounts.planned} planned (${scope.packageCount} packages)`,
    ""
  ];
  for (const stage of roadmap.stages) {
    lines.push(`## ${stage.id} - ${stage.name}`);
    lines.push("");
    lines.push(`Stage state: **${stageStatus(stage, packageMap, roadmap.activePackageId)}**`);
    lines.push("");
    lines.push("| Package | Build/phase | Work | State | Estimate |");
    lines.push("| --- | --- | --- | --- | ---: |");
    for (const packageId of stage.packageIds) {
      const item = packageMap.get(packageId);
      const state = item.id === roadmap.activePackageId ? "ACTIVE" : item.status.toUpperCase();
      lines.push(`| ${item.id} | ${item.phase} | ${item.name} | ${state} | ${estimateLabel(item)} |`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

function currentPlan() {
  return renderPlan(loadRoadmap(), loadRegister(), readJson("package.json"));
}

if (require.main === module) {
  const outputPath = path.join(root, "outputs", "Plan-Status.md");
  const output = currentPlan();
  if (process.argv.includes("--write")) {
    fs.writeFileSync(outputPath, output);
    console.log("Updated outputs/Plan-Status.md");
  } else {
    process.stdout.write(output);
  }
}

module.exports = { loadRoadmap, validateRoadmap, renderPlan, currentPlan };
