window.LTP_COMMAND_BINDINGS = Object.freeze({
  commandPalette: [{ key: "k", primary: true }],
  openAssumptionWorkbench: [{ key: "a", primary: true, shift: true }],
  showHints: [{ key: "h" }],
  toggleMultiSelect: [{ key: "m" }],
  moveSelectionToParent: [{ key: "p", command: true }],
  chooseSelectionFrame: [{ key: "f", command: true }],
  createNode: [{ key: "n" }],
  createParentNode: [{ key: "a", shift: true }],
  createSupportingNode: [{ key: "a", shift: false }],
  focusInspector: [{ key: "Enter" }],
  beginConnection: [{ key: "l" }],
  createFrame: [{ key: "f" }],
  selectParentFrame: [{ key: "[" }],
  enterSelectedFrame: [{ key: "]" }],
  focusSearch: [{ key: "/" }],
  togglePin: [{ key: "p" }],
  toggleFrameCollapsed: [{ key: "x", primary: true }, { key: "-" }],
  previewNode: [{ key: " " }],
  cancelContext: [{ key: "g", control: true }],
  undo: [{ key: "z", primary: true, shift: false }],
  redo: [{ key: "z", primary: true, shift: true }, { key: "y", primary: true }],
  deleteSelection: [{ key: "Delete" }, { key: "Backspace" }, { key: "d", control: true }],
  cycleNodeTypes: [{ key: "Tab", shift: true }],
  panUp: [{ key: "ArrowUp" }, { key: "p", control: true }],
  panDown: [{ key: "ArrowDown" }, { key: "n", control: true }],
  panLeft: [{ key: "ArrowLeft" }, { key: "b", control: true }],
  panRight: [{ key: "ArrowRight" }, { key: "f", control: true }],
  centerSelection: [{ key: "c" }],
  zoomIn: [{ key: "=", primary: true }, { key: "+", primary: true }],
  zoomOut: [{ key: "-", primary: true }],
  resetZoom: [{ key: "0", primary: true }],
  fitView: [{ key: "1", primary: true }],
  toggleLeftPanel: [{ key: "[", alt: true }],
  toggleRightPanel: [{ key: "]", alt: true }],
  runAutoLayout: [{ key: "l", primary: true, shift: true }]
});

window.LTP_COMMAND_LABELS = Object.freeze({
  commandPalette: "Command palette",
  openAssumptionWorkbench: "Open Assumption Workbench",
  showHints: "Toggle hints",
  toggleMultiSelect: "Start multiple selection",
  moveSelectionToParent: "Move selection to parent frame",
  chooseSelectionFrame: "Move selection to a frame",
  createNode: "Create node",
  createParentNode: "Create parent condition",
  createSupportingNode: "Create supporting condition",
  focusInspector: "Edit selected element",
  beginConnection: "Create link",
  createFrame: "Create frame",
  selectParentFrame: "Select parent frame",
  enterSelectedFrame: "Enter selected frame",
  focusSearch: "Search",
  togglePin: "Toggle pin",
  toggleFrameCollapsed: "Minimize or expand selected frame",
  previewNode: "View full statement",
  cancelContext: "Cancel or clear selection",
  undo: "Undo last change",
  redo: "Redo last change",
  deleteSelection: "Delete selection",
  cycleNodeTypes: "Cycle selected entity types",
  panUp: "Move view up",
  panDown: "Move view down",
  panLeft: "Move view left",
  panRight: "Move view right",
  centerSelection: "Center selection",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  resetZoom: "Reset zoom",
  fitView: "Fit diagram",
  toggleLeftPanel: "Toggle left panel",
  toggleRightPanel: "Toggle right panel",
  runAutoLayout: "Run automatic layout"
});
